In [1]:
import numpy as np

In [2]:
arr=np.array([1,25,33])

In [3]:
arr

array([ 1, 25, 33])

In [4]:
arr2=np.array([[1,2,3],[2,34,5]])

In [5]:
arr2

array([[ 1,  2,  3],
       [ 2, 34,  5]])

In [6]:
arr.ndim

1

In [7]:
arr2.ndim

2

In [14]:
arr3=np.array([[[23,45,65],[43,64,2],[4,2,5]],[[2,5,5],[4,4,32],[4+2,2-1,5+4]]])

In [15]:
arr3

array([[[23, 45, 65],
        [43, 64,  2],
        [ 4,  2,  5]],

       [[ 2,  5,  5],
        [ 4,  4, 32],
        [ 6,  1,  9]]])

In [10]:
arr3.ndim

3

In [11]:
arr[2]

33

In [13]:
arr[:2]

array([ 1, 25])

In [19]:
arr2[1,0:2]

array([ 2, 34])

In [21]:
arr3[1,0:2,1:]

array([[ 5,  5],
       [ 4, 32]])

In [22]:
arr3[0,1,2]

2

In [24]:
arr3[1,1,1:]

array([ 4, 32])

In [2]:
import numpy as np

In [4]:
# create a numpy arry from dataset
temperature_data = [25.3, 26.1, 24.8, 23.5, 27.2]
pressure_data = [101.2, 100.8, 101.5, 100.2, 101.0]
humidity_data = [55.2, 54.8, 56.5, 53.7, 55.9]

tarr=np.array(temperature_data)
parr=np.array(pressure_data)
harr=np.array(humidity_data)

In [7]:
tarr

array([25.3, 26.1, 24.8, 23.5, 27.2])

In [6]:
# Calculate mean of each quantity
tempAvg=np.mean(tarr)
pressureAvg = np.mean(parr)
humAvg = np.mean(harr)

In [8]:
tempAvg

25.380000000000003

In [14]:
#calculated SD for each quantity
tempSD=np.std(tarr)
pressureSD = np.std(parr)
humSD = np.std(harr)

In [15]:
tempSD

1.2416118556135003

In [17]:
#calculate max and min value of the temperature
tempMax = np.max(tarr)
tempMin= np.min(tarr)

In [18]:
tempMax

27.2

In [19]:
tempMin

23.5